# Generated by Django 4.2 on 2023-04-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texton', '0002_employer_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('Businessemail', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('Jobtitle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'flow',
            },
        ),
    ]
