# Generated by Django 4.2 on 2023-04-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texton', '0003_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venuename', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Zip', models.IntegerField()),
                ('Contact_number', models.IntegerField()),
                ('webaddress', models.CharField(max_length=50)),
                ('Emailaddress', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'venue',
            },
        ),
    ]
