# Generated by Django 4.2 on 2023-04-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texton', '0004_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='Address',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='venue',
            name='Emailaddress',
            field=models.CharField(max_length=59),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venuename',
            field=models.CharField(max_length=66),
        ),
        migrations.AlterField(
            model_name='venue',
            name='webaddress',
            field=models.CharField(max_length=90),
        ),
    ]
